# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.6.1
_src_path: gh:oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Odoo Community Association (OCA)
org_slug: OCA
rebel_module_groups: []
repo_description: This project focus on payment interface
repo_name: OCA banking payment addons for Odoo
repo_slug: bank-payment
repo_website: https://github.com/OCA/bank-payment
travis_apt_packages: []
travis_apt_sources: []
